### ISSUE TITLE
Crashing on Mod Settings changes

### ISSUE THREAD

**Issue by Darrenc134** [jayugg/BalancedThirst#4]
When Mod Settings are edited in game on a dedicated server and client leaves and tries to rejoin the server the game crashes. the problem was fixed 1 time by deleting config files in client and the dedicated server.

**Comment by Darrenc134** [comment]
Running on 64 bit Windows 10.0.19045.0 with 32709 MB RAM
Game Version: v1.19.8 (Stable)
7/15/2024 8:38:15 PM: Critical error occurred in the following mod: balancedthirst@0.0.30
Loaded Mods: aculinaryartillery@1.1.5, balancedthirst@0.0.30, bettercrates@1.7.1, blacksmithname@1.1.7, chiseltools@1.12.3, decor@1.1.1, entitiesinteract@1.0.10, extrachests@1.8.0, millwright@1.1.5, oils@1.2.1, primitivesurvival@3.5.7, qptech@1.15.2, vintageengineering@0.1.4, game@1.19.8, alchemy@1.6.34, animalcages@3.0.2, animationmanagerlib@0.8.8, apewindows@1.0.0, egocaribautomapmarkers@3.1.0, betterruins@0.3.5, butchering@1.6.1, carryon@1.7.4, commonlib@2.4.0, electricity@0.0.11, expandedfoods@1.6.9, freedomunits@1.1.4, fromgoldencombs@1.4.32, herbarium@1.2.0, hudclock@3.4.0, inquisitor@1.0.1, knapster@2.9.5, liquidcontainers@1.2.0, medievalexpansion@3.13.1, moreanimals@1.3.5, petai@2.2.6, playerlist@2.1.2, claywheel@1.1.1, prospecttogether@1.3.0, qpclienttools@1.0.1, sailboat@1.3.1, scarecrow@1.4.3, storagecontroller@1.0.11, thatsenoughinventory@1.0.2, thecritterpack@0.9.1, vinconomy@0.2.10, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, vsvillage@1.0.5, cats@2.0.2, configlib@1.3.13, em@2.6.3, feverstonehorses@1.6.1, foxtaming@1.4.0, simplewinddirection@1.0.2, stonequarry@3.3.1, tpnet@1.14.3, treetapping@1.0.0, vsvillageaged@0.0.1, wolftaming@2.1.2, bricklayers@2.5.5, entitiesconfiguration@1.0.6, tailorsdelight@1.5.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at BalancedThirst.Hud.ThirstBarHudElement.OnFlashStatbars(Single dt) in /Users/jacopouggeri/workspace/VintageModding/BalancedThirst/BalancedThirst/Hud/ThirstBarHudElement.cs:line 135
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 19
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 81
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 838
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/15/2024 8:25:39 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2260
Faulting application start time: 0x01dad71683e5ef22
Faulting application path: C:\Users\Darre\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Darre\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: d8f7e9a7-1b48-4e82-8467-2997668ed2df
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 7/15/2024 8:06:13 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2468
Faulting application start time: 0x01dad713d64a5e9e
Faulting application path: C:\Users\Darre\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Darre\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: a78f4a7e-ceae-400d-b9ff-66cb5c240667
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 7/15/2024 8:02:02 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x4d70
Faulting application start time: 0x01dad71343957f13
Faulting application path: C:\Users\Darre\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Darre\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: e23262ca-3bfe-4fcb-a486-8b118fc2167e
Faulting package full name: 
Faulting package-relative application ID:  }
