### ISSUE TITLE
crash on mouse over stew with non vanilla ingredients in inventories

### ISSUE THREAD

**Issue by LarekFlynn** [jayugg/BalancedThirst#5]
the bowls of food also can't be eaten.
first crash was salmon-perch stew with boiled cranberries(whole fish from primitive survival)
second from bushmeat and fish stew(fish meat from primitive survival, bushmeat allowed in stew by expanded foods)

Running on 64 bit Windows 10.0.19045.0 with 32711 MB RAM
Game Version: v1.19.8 (Stable)
08/23/24 12:41:59 PM: Critical error occurred in the following mod: balancedthirst@0.0.38
Loaded Mods: detonateredux@1.1.1, degrees1499@1.0.0, acorns@0.5.3, aculinaryartillery@1.1.5, advancedsmithing@1.3.0, africanmonitorlizards@1.0.7, Armorlite@1.1.0, arrowheadsrecovery_fork@1.0.0, asianmonitorlizards@1.0.1, atwatersedge@1.4.1, axleinblocks@1.19.8-rc.1, balancedthirst@0.0.38, bamboom@0.2.1, bandedgeckos@1.2.0, beardeddragons@1.0.0, betterbricks@1.1.1, bettercompost@1.0.2, easyjam@1.0.0, bettershears@1.0.0, irregularguyboltheadsrecovery@1.0.1, explosivevanvar@0.0.5, buckets_stack_to_5@1.0.1, buzzwords@1.7.0, cairns11bigcairn@1.1.0, cellardoor@1.4.0, charcoalpitrebalance@1.0.1, chiblocksel@1.0.5, chiseltools@1.12.3, claycasting@1.1.5, Clothez@1.0.0, compass2@3.0.0, landformoverhaul@0.0.2, coreblast@0.1.2, crackedrockweak@1.0.0, craftingjonas@1.0.6, creaturescan@1.0.10, cumanhelmet@0.7.5, CutTheFat@1.0.0, decor@1.1.4, directstrongtannin@1.0.0, dont-place-sticks@1.0.1, dryable_ground_storage@1.0.0, DrystoneParity@1.0.0, dye_recipes_fix@1.0.0, eldritchcuteclothing@1.0.2, ensatinas@1.0.0, entitiesinteract@1.0.11, evaporite@1.0.0, explosive@0.0.5, extendedcrafts@1.1.4, morecropsfix@1.0.6, fernslikegrass@1.1.0, fibersfromtwine@1.0.1, fieldsofgold@2.1.6, firewoodfrombamboo@1.0.0, fixture@1.0.2, flourbags@1.0.4, caninae@1.0.16, capreolinae@1.1.5, casuariidae@1.0.8, dinornithidae@0.7.0, machairodontinae@1.0.9, manidae@1.0.2, pantherinae@1.1.9, rhinocerotidae@1.0.3, sirenia@1.0.5, free_stone_drops_when_broken@1.0.1, geoaddons@1.3.5, giantgouramis@1.0.2, gildedsteel@1.0.5, hammercrushed@1.0.0, HangingOilLamps@1.0.1, healthiertrees@1.0.0, hideandfabric-net7u@1.3.1, immersivecorpsedrop@1.0.2, indappledgroves@0.8.3, ingotheating@1.0.2, juicyores@1.0.0, knappingmastery@1.0.1, knobtailedgeckos@1.2.1, lanternliner@0.1.0, lanternpost@1.0.8, leopardgeckos@1.2.2, lithocraft@0.2.0, longtermfood@0.0.5, meatup@0.1.1, meltingpp@1.0.3, metaldetector@1.0.1, millwright@1.1.6, molds@0.0.6, morecrystals@1.2.0, moredrygrass@0.2.0, morenails@1.1.0, moreparchment@1.0.0, MoreTorchHolders@1.0.0, mycodiversity@1.0.2, nacatfish@1.0.1, nadarters@2.0.0, nasalamanders@1.0.0, naturalclay@1.1.1, newworldgianttortoises@1.1.1, pondfrogsiii@1.2.3, newzealandfrogs@1.1.1, unochre@1.2.0, oils@1.2.2, pondfrogsi@1.2.3, orepulverizer@1.1.1, pacificnewts@1.3.1, PartialLandslides@1.0.0, peacockbasses@1.1.2, pipeleaf@1.8.0, primitivesurvival@3.6.4, proximityprospectingpick@1.0.1, unpfix@1.0.0, quicklimepk@1.0.0, rainfrogs@1.2.1, bpip@0.0.8, realshingles@1.0.2, ripened_wild_crops@1.0.0, rlmoonsun@0.1.2, rope-bridges@1.1.0, saltandsands@1.0.2, salty@1.0.1, scatastrophe@1.1.2, she1fish@1.2.1, shepherdmod@1.0.2, simplerails@1.0.0, speararrowheadbits@1.1.0, SpeedBoostCraftables@1.0.2, spiderwebtwine@0.0.1, sticksfromfirelogs@1.3.0, superfuelresumed@2.1.3, swordz@1.1.8, litbrig@0.5.0, thatchexpanded@1.1.1, truesunfishes@1.1.2, untamedwildsursidae@1.0.8, usefuldrifterloot@1.1.0, viesblocks@2.4.10, vintage-symphony-assets@1.0.0, vintage-symphony@0.9.2, game@1.19.8, wallpaperblocks@2.0.0, wallpaper@1.0.0, warriordrink@1.0.2, zoombuttonreborn@1.8.0, abcsreborn@0.2.2, alchemycompat@1.0.0, alchemy@1.6.34, all_crates_matter@1.0.0, ancienttools@1.5.18, animationmanagerlib@0.8.8, apewindows@1.1.0, artofgrowing@0.0.4, augplantlib@0.0.3, flags@0.33.0, beartrap@1.1.1, bedspawnv2@1.2.0, beehivekiln@1.6.1, beltcraft@1.0.0, betterbloomeriesreborn@1.0.5, bettercaveart@1.1.1, betterfirepit@1.1.4, betterhewnfencegates@1.0.0, betterstonepath@1.0.3, biggercellars@1.0.0, blacksmithenhancements@1.0.5, bodyheatbarfix@1.0.1, butchering@1.6.6, butterflycases@1.0.1, cancrops@0.1.27, canjewelry@0.2.42, carryon@1.7.4, chickenfeed@1.1.3, clearerquartzfix@1.0.0, clipfix@2.0.2, Clumps@1.0.0, commonlib@2.5.0-rc.2, composter@1.1.0, Crateful@1.2.8, creaturekilledby@1.0.0, crosscomme@1.0.10, cuniculture@1.0.2, danatweaks@3.1.0, darkerdrifterspawns@1.0.1, deconstructchutes@1.0.1, displaycasewall@1.0.3, doubleslabs@0.1.1, kdynamicjump@1.0.0, electricity@0.0.11, evenjugincrements@1.0.0, expandedfoods@1.7.0, extrachutes@1.0.0, extrainfo@1.8.1, fancyplanters@1.2.0, helfavorite@0.3.5, fenceclimbable@1.0.0, fieldsofsalt@1.2.1, foodshelves@1.1.3, fromgoldencombs@1.6.2, furniturelibrary@1.0.11, golb@1.0.0, hangingbaskets@1.1.0, hardcoreutilities@1.2.0, heatretention@1.0.2, herbarium@1.2.0, hit@2.1.1, hydrateordiedrate@1.2.0, immersivetpscamera@1.0.5, itemframe@1.0.0, kegrevivedagain@1.1.0, kevinsfurniture@1.2.0, kscartographytable@1.0.1, lavoisier@1.3.0, lib2d@1.0.0, lichenredux@1.8.3, liquidcontainers@1.2.0, lubricant@1.2.2, maltiezbows@1.0.4, medievalexpansion@3.13.1, metaltongs@1.1.3, mio@0.9.5, meteoricexpansion@1.2.5, middleclicktostow@1.0.0, mif@1.0.1, moreanimals@1.3.5, morepiles@1.5.0, moreplaster@1.0.2, mouse4and5@2.0.0, mcrate@1.2.1, mushroomz@1.0.2, naturalnight@2.1.0, norottinghides@1.0.0, spearexpantion@0.1.8, particlesplus@1.1.0, passthruchutes@1.0.1, simplewinddirectionpelagus@1.0.0, petai@2.2.6, pigfeed@1.0.4, pileful@1.1.5, pomshadercache@1.1.1, postsandbeams@1.3.2, claywheel@1.1.1, powdermanufacturing@0.0.2, RareDenseOres@0.2.6, redbricktweak@1.0.0, resurgencepack@1.6.0, rivers@3.1.0, rockstratavariety@0.0.1, sailboat@1.3.1, scarecrow@1.5.0, seashellore@1.0.0, simplecloth@1.0.2, simplefootstepsredux@1.0.0, somethinginthewater@1.2.4, starvation@1.0.5, steamandpower@1.6.0, steelanvil@1.0.0, stillnecessaries@1.1.2, stonebakeoven@1.1.3, survivalexpanded@0.2.3, tarmor@0.2.2, thecritterpack@0.9.1, thirdperson_crosshair@1.0.0, toolworks@1.8.1, trailmod@1.0.8, tstools@2.1.2, usefulstuff17@1.3.2, vanillacratecompatibility@1.0.0, vanvar@5.0.4, versionchecker@1.0.0, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, warmarmor@1.1.0, wgmt@1.0.1, whatbagwasthatagain@1.0.1, wildfarmingrevival@1.2.4, workbenchexpansion@1.8.0, xlib@0.8.6, yummyfoods@1.0.4, alchemistry@1.0.2, metalrecovery@0.1.19-pre.1, beehivekilnwithclay@1.0.0, betterbamboo@1.0.2, bookbinders@1.0.0, bugnetcompatibility@1.0.1, bullseye-continued@2.5.8, cancropsprimitivesurvivalcompat@1.0.3, configlib@1.3.13, constructionsupport@0.1.2, dowsedinsalt@1.0.0, electricityaddon@0.0.6, electricityextensions@0.0.7, em@2.7.0, extraoverlays@1.4.0, feverstonehorses@1.6.1, flammablefirestarter@1.0.1, fruitpresstweaked@1.0.1, fsmlib@0.4.5, glassmaking@1.4.0, justchairs@0.0.1, morecandles@1.2.2, morefloors@2.1.1, newworldcrops@0.0.8, onestick@1.0.1, pickupartist@0.2.0, pickupfast@1.0.2, plankable-nmnd@0.1.2, helquickstack@0.4.2, RedDyeFromBerries@1.1.1, slanted_display_cases@1.3.2, expandedfoodscheese@1.0.0, stainedbeams@1.0.0, cookie12000stickbeam@1.1.0, stonepiles@1.1.2, stonequarry@3.3.1, talderzeit@0.1.0, toolworksadditions@1.3.2, treetapping@1.0.0, Uncrustables@1.0.0, vanity@2.2.0, vsrecipes@1.2.2, wattleworldrevised@1.1.0, wildcraftfruit@1.2.1, wildcraftherb@0.0.1, wildcrafttree@1.1.0, xinvtweaks@1.6.6, xskills@0.8.8, bricklayers@2.5.6, cancropsxskillscompat@1.0.7, chickenfeedwildcraftfruitcompat@1.0.0, maltiezcrossbows@0.3.11, maltiezfirearms@0.5.4, maltiezspears@0.1.6, maltiezswords@0.0.1, ropebridgescompatibility@1.0.0, statushudcont@2.1.1, tailorsdelight@1.5.10, ashes@1.0.0, wildberrydye@0.0.1, wildcrafteggshelltroughfix@1.0.0, xskillscatchablepatch@1.1.1, banners@0.1.1, bricklayerglassmakingcompat@1.0.2, dressmakers@1.4.0, upholstery@1.0.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at BalancedThirst.Thirst.HydrationProperties.op_Addition(HydrationProperties a, HydrationProperties b) in /Users/jacopouggeri/workspace/VintageModding/BalancedThirst/BalancedThirst/Thirst/HydrationProperties.cs:line 103
   at BalancedThirst.Util.Extensions.GetHydrationProperties(CollectibleObject collObj, IWorldAccessor world, ItemStack itemStack, Entity byEntity) in /Users/jacopouggeri/workspace/VintageModding/BalancedThirst/BalancedThirst/Util/Extensions.cs:line 86
   at BalancedThirst.HarmonyPatches.Meal.BlockMeal_GetHeldItemInfo_Patch.Postfix(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in /Users/jacopouggeri/workspace/VintageModding/BalancedThirst/BalancedThirst/HarmonyPatches/Meal/BlockMeal_GetHeldItemInfo_Patch.cs:line 18
   at Vintagestory.GameContent.BlockMeal.GetHeldItemInfo_Patch5(BlockMeal this, ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 401
   at Vintagestory.Client.NoObf.HudMouseTools.OnRequireInfoText(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 167
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 142
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 208
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerOnMouseEnterSlot(ClientMain game, ItemSlot slot) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 514
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 809
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 512
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 608
   at Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 433
   at Vintagestory.Client.NoObf.ClientMain.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1980
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition() in VintagestoryLib\Client\ClientPlatform\Input.cs:line 111
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by jacopouggeri** [comment]
I tested the newest version (0.0.40) with a primitive survival catfish and blueberry stew and it worked fine after a slight edit. Can you check if you still get this crash on this version?

**Comment by LarekFlynn** [comment]
No more crashes since updating so seems all good
